### ISSUE TITLE
about the perform_1D_search and perform_2D_search

### ISSUE THREAD

**Issue by andeyeluguo** [wimh966/QDrop#10]
perform_1D_search 表示 对只有正值或负值的进行搜索，perform_2D_search表示对有正负值的进行搜索，但是里面的如何搜索的看不出来什么原理，有什么参考资料吗
https://github.com/wimh966/QDrop/blob/f1162c94e52bc7e95c577333e436a00f11398100/quant/quant_layer.py#L167

**Comment by wimh966** [comment]
Usually, when we take the ReLU as the activation function, the activations all fall into the positive part. You can imagine what we need to do is to decide the one-side clipping range. However, when there is no ReLU, the activations can also fall into the negative part. For asymmetric quantization setting, we need to decide two-side clipping range. So we need to conduct 2-D search.
