### ISSUE TITLE
confused about activation quantization

### ISSUE THREAD

**Issue by Jan017** [wimh966/QDrop#12]
Few questions about activation quantization.
- in  the real depolyment,we always fuse the activations,so why we need to quantize the activation output.
- to the best of my knowledge , normally what activation function does is that to clip the value calculated by the previous layer. By doing activation quantization,we clipped the quantized value by using  an quantized activation funciton. It's quite reasonable. So could you please give me some explanation or more intuition about why we need to adjust or fine tune the quantized activation?

**Comment by wimh966** [comment]
For the first question, I don't understand it. In real deployment, we actually need to quantize the activation output. It's the Quantize process that will be combined with the Dequantize Process in previous layers and become the Re-Quantize Process. The activation is quantized.

For the second question, We do not adjust the quantized activation. But we make the weight or the quantized weight to see the quantization of activation. If we do not incorporate the activation quantization during weight tuning, then imagine that for different activation bit-width, the tuned quantized weight will the same.

**Comment by Jan017** [comment]
thank for your explanation. In [onnx](https://onnxruntime.ai/docs/performance/graph-optimizations.html), graph optimization will be applied. Thus we can fuse activation into previous layers. so i'm quite confused about if we can fuse activation into its previous layer,shall we need to quantize it?

**Comment by wimh966** [comment]
You can check the onnx models, you will find there are still quantization parameters. We just merge the quantization parameters called as ReQuantize process.
