### ISSUE TITLE
关于检测模型的代码

### ISSUE THREAD

**Issue by XpracticeYSKM** [wimh966/QDrop#15]
您好，非常感谢您这么优秀的工作，代码仓库中只看到了ImageNet的相关代码，请问能否开源检测任务上的相关代码呢，非常感谢！

**Comment by wimh966** [comment]
您好，我们会考虑最近开源检测的代码。这需要一些时间来整理代码。

**Comment by wimh966** [comment]
Hello, QDrop for detection tasks (MS COCO) is available now. Thanks for your attention and suggestion.

**Comment by XpracticeYSKM** [comment]
Thanks！I can't find detection code in this repo, where should i find it?

**Comment by XpracticeYSKM** [comment]
where should i see

**Comment by XpracticeYSKM** [comment]
Thanks！
But I can't find the detection code in this repo ,where should I go?
