### ISSUE TITLE
如何获取量化后的weight和input

### ISSUE THREAD

**Issue by Arthur-Ling** [wimh966/QDrop#16]
你好，我尝试从imagenet_utils.validate_model(val_loader,model)中加hook获取量化后的input和weight,但是失败了,似乎validate_mode里面的仍然是以浮点类型进行的运算。请问如何可以获得量化后模型的整型input,和weight?
谢谢

**Comment by wimh966** [comment]
Hello, the key part is to get the quantization parameters (scale, zero point) and tuned weight. Once you get these, you can apply only the "quantize" function to tuned weights and activations (e.g., clip(round(x/s)+zp), quant_min, quant_max). Then you can get quantized weights and activations. 

In this code, we use fake quant function which includes "quantize" and "dequantize" functions to obtain the accuracy more conveniently. That's the reason you see the FP calculation. In real development, "dequantize" function will be moved later and fused with others.

Hope these would be helpful to you.

**Comment by qifeng22** [comment]
@wimh966 Does the inference accuracy of fake quantization equal the on-device quantization?
