### ISSUE TITLE
"mse" 中 p 的取值

### ISSUE THREAD

**Issue by rainyBJ** [wimh966/QDrop#2]
您好，想问一下，为什么这里的 p 用的是 2.4 呀？
``` python
# L_p norm minimization as described in LAPQ
# https://arxiv.org/abs/1911.07190
score = lp_loss(x, x_q, 2.4, reduction='all')
```

**Comment by wimh966** [comment]
copy的BRECQ代码，可以使用2，我觉得对于这类会微调的算法影响不大

**Comment by rainyBJ** [comment]
哦哦，了解了解，还想请教一下在进行 Block Reconstruction 的时候，速度特别慢，请问可以通过什么操作来改善嘛？

**Comment by wimh966** [comment]
将提前计算到的block的input和output放在gpu上，现在是默认放在cpu上，forward的时候再放在gpu上。一般r18等这些数据可以直接放在gpu上。keep_gpu=False，这个参数。

**Comment by rainyBJ** [comment]
照您说的改了一下，确实速度会快一些，感谢！您提到 r18 可以直接放到 GPU 上，是存在其他情况不能这样子做嘛？

**Comment by wimh966** [comment]
看显存够不够，因为需要提前存下来block input和output。如果你的机器显存不够+大模型会OOM。

**Comment by rainyBJ** [comment]
了解了解，感谢您的回复！很棒的工作！
