### ISSUE TITLE
Can't reproduce results on Resnet18

### ISSUE THREAD

**Issue by ofirgo** [wimh966/QDrop#20]
Hello,

I'm trying to reproduce the results from the paper (Table 3) for ResNet18 (on ImageNet) but I'm getting an accuracy that is 0.5-0.7% in all cases. 
I tried the given config for W2A4 and also W4A4, both with different random seeds. All attempts separately and the average results came out smaller than expected.
I also tried to compare the results without the 8-bit for the first and last layers restriction and got a similar accuracy drop compared to the relevant results from the paper.

I will appreciate your support in understanding if there is some issue here, although I didn't change anything in the code...

Thanks in advance.

**Comment by wimh966** [comment]
Hello, thanks for your question. May I kindly ask which branch are you using? I think we shall use the branch qdrop. And can you share your log with me? Considering the results you get are all 0.5-0.7%, which sounds a little strange. So if it is convenient for you, can you also have a try with the W8A8 setting? These can make us have a check more easily. Thank you.

**Comment by ofirgo** [comment]
Hi @wimh966 , thank you for the response.

Yes, I'm running the qdrop branch.
The result I'm getting for W8A8 is: 71.004

The log of the W4W2 run (with the default r18/config, without any changes to the coce) is attached.
Also, I'm using Python 3.10.13 and torch 2.0.1 if it matters.
[resnet18_w4a2_log.txt](https://github.com/wimh966/QDrop/files/13349785/resnet18_w4a2_log.txt)

**Comment by wimh966** [comment]
Hi! It seems that I misunderstood your problem. I thought all the results were 0.5%-0.7%. But the result you are giving now is actually 64+. Thus, do you mean that the results you obtained are 0.5%-0.7% lower than the paper? May I have your accuracy results of W2A4 and W4A4? And does other models also have such a problem?  You do not need to change the random seed and I think the torch and python versions do not matter. 

For the first and last layer 8-bit setting, I'd like to make it clear that it actually means making the inputs of the first and last layer 8-bit. It corresponds to the line without \dag signal in the Table 3. Results you get shall be consistent with lines without \dag signal. For the line with \dag signal in the Table 3, we additionally make the second layer's input 8-bit as well to align the setting in the paper BRECQ. If you want to enable this, you need to additionally change the bit-width of one activation.

**Comment by ofirgo** [comment]
Ok, so it seems that I misunderstood something as well.

First of all, regarding the lower results - yes, I meant 0.5-0.7% worse than the reported results in the paper, sorry for the misunderstanding.
But after your answer, I think that maybe I didn't compare to the right result, so let's see if I got it right now:

The default W2A4 config in the r18/config.yaml with the default settings in the code matching the result without the \dag signal? That is, 64.66? I got 64.55 in this case which I guess is fine, I just compared it to the result with the \dag signal (65.25).
Similarly, for W4A4 I got 69.078 but compared it to the 69.62 results (with the \dag), where, if I understand you correctly, I should have compared it to the 69.1 results (and then the drop is minor).

So let me get this straight - all results in the paper refer to a model where the first and last linear layer weights are quantized to 8-bit whatsoever, plus the activation after the last convolution is quantized with 8 bits? This matches the results without the \dag signal?
Does that mean that none of the results refer to a case where **all** linear ops weights and activations are quantized to the specified bitwidth (say 4 and 2)?

**Comment by wimh966** [comment]
Yes, you understand these correctly. If you want to make all the layers to specific bit-width, you can also enable it. I remember that giving low-bit to weight of the first and last layer can affect the accuracy much (not very sure). Thus, it's usually the case that many papers adopt the first and layer layer 8-bit setting. For the input of the first layer, it has been in the range 0-255. But for the input of second layer, I find that it really affects, especially on low-bit like W2A2 and light-weight structures like Mbv2.

**Comment by ofirgo** [comment]
Thank you very much for the clarification.

**Comment by wimh966** [comment]
OK. So I kindly close this issue.
