### ISSUE TITLE
The optimization order

### ISSUE THREAD

**Issue by tojiboyevf** [wimh966/QDrop#21]
Thanks for your work!
I have a question regarding the optimization order. 
In BRECQ, authors first separately perform AdaRound then they optimize input quantization parameters. But in your implementation you jointly optimized both parameters. Does this approach give better performance than BRECQ's?

**Comment by wimh966** [comment]
Hi, you can see results about different orders in the first part of the
method. Brecq and adaround corresponds to the case 1, while letting the
weights learn with quantized activations can be much better, which
corresponds to the case 2 and 3.

**Comment by tojiboyevf** [comment]
Understand 
Thank you for your response 👌
