### ISSUE TITLE
Questions about “set_first_last_layer_to_8bit” function

### ISSUE THREAD

**Issue by jiangaojie** [wimh966/QDrop#3]
hello，in the  “set_first_last_layer_to_8bit” function at quant_model.py,What role does this sentence “module_list[-2].act_quantizer.bitwidth_refactor(8)” play？It is not the last layer in the resnet18. Actually i find it is the stage4.unit2.conv2 module but its act_quantizer is disabled.
I want to know what the purpose of this sentence is。thank you very much If you answer my question

**Comment by wimh966** [comment]
"set_first_last_layer_to_8bit" means setting the input of the first and last layer's input to 8-bit. As the first layer with pixels in [0, 255] naturally matches with 8-bit, so just need to set last layer's input 8-bit. "module_list[-2].act_quantizer.bitwidth_refactor(8)" means  the penultimate layer's output to 8-bit thus the last layer input matches with 8-bit value.

**Comment by jiangaojie** [comment]
See light suddenly！ thank you very much， great job！
![image](https://user-images.githubusercontent.com/50157848/168036212-c343eeca-b91b-47bf-829f-dbc9b31e2b18.png)

But I'm still confused about “module_list[-2].act_quantizer.bitwidth_refactor(8)”，in the resnet18，the module_list[-2] is the module that is framed in red at the figure. but its act_quantizer is disabled becasue you apply activation quantization after element-wise add, Therefore, this element-wise add layer(penultimate layer) is not quantized by 8bit, but 4bit or 2bit ？
thank you very much If you answer my question

**Comment by wimh966** [comment]
Sorry for late. I've got it. It seems that we indeed didn't turn on the "last layer input 8-bit" setting but keep it in 2/4-bit. I think, if we fix it, the results can be further enhanced. Thank you very much for pointing out this!. I'll fix it and give a clearer version during next two weeks (these days are very busy with other things.).

**Comment by jiangaojie** [comment]
Thank you！

**Comment by jiangaojie** [comment]
Hello,Can you open source Object detection code？

**Comment by wimh966** [comment]
I write this using company internal framework. Details are described in the paper. Or you can see MQbench and EOD for substitute.

**Comment by wimh966** [comment]
> See light suddenly！ thank you very much， great job！ ![image](https://user-images.githubusercontent.com/50157848/168036212-c343eeca-b91b-47bf-829f-dbc9b31e2b18.png)
> 
> But I'm still confused about “module_list[-2].act_quantizer.bitwidth_refactor(8)”，in the resnet18，the module_list[-2] is the module that is framed in red at the figure. but its act_quantizer is disabled becasue you apply activation quantization after element-wise add, Therefore, this element-wise add layer(penultimate layer) is not quantized by 8bit, but 4bit or 2bit ？ thank you very much If you answer my question

Hi, I've updated my code  and it's ok now. And I also provide another form of code based on the design style of quantization struction in MQbench. You can use any one as you like. Thanks for your interest of our work. If you have any further questions, just let me know!

**Comment by andeyeluguo** [comment]
> "set_first_last_layer_to_8bit" means setting the input of the first and last layer's input to 8-bit. As the first layer with pixels in [0, 255] naturally matches with 8-bit, so just need to set last layer's input 8-bit. "module_list[-2].act_quantizer.bitwidth_refactor(8)" means the penultimate layer's output to 8-bit thus the last layer input matches with 8-bit value.

I think the first layer's input is not in [0, 255], because the 
https://github.com/wimh966/QDrop/blob/f1162c94e52bc7e95c577333e436a00f11398100/data/imagenet.py#L23
has the normalize operation which normalize to [-1, 1].
