### ISSUE TITLE
Unable to reproduce the results in paper

### ISSUE THREAD

**Issue by caltonhao** [wimh966/QDrop#4]
您好，我采用run.sh的默认参数以及pretrain model，此时设置了第一层和最后一层为8bit，在ResNet18上跑出量化结果为：
1. w2a2：50.73
2. w3a3：65.32
3. w2a4：64.57
都达不到论文里面的结果。
您这边大概知道可能的原因吗？

**Comment by wimh966** [comment]
感觉和论文里面差距就是0.5以内啊？论文里面是w2a4: 64.66。w3a3: 65.56。w2a2: 51.14

**Comment by caltonhao** [comment]
> 

不是的，上面我跑的结果是设置了第一层和最后一层8bit的，跟论文差距还挺大的。

**Comment by wimh966** [comment]
我看一下哦。但是论文里面写了是设置了首尾8bit的。

**Comment by wimh966** [comment]
您好，我检查过了，代码和论文是相符的。请您仔细阅读论文提及的设定，谢谢。
