### ISSUE TITLE
Question for case setting  in paper

### ISSUE THREAD

**Issue by jiawei-liu1103** [wimh966/QDrop#5]
您好，非常感谢你们的工作，在这里我想问一下关于论文中case2和case3的问题。 文中你们指出case3没对当前block的激活进行量化，但是我在阅读你们的代码时发现在进行block重建时你们计算损失是在对激活量化之后进行的。
`err = loss_func(out_quant, cur_out)`
这里的`out_quant`是对激活进行量化之后的特征，所以我想知道case2和case3的区别。
谢谢！

**Comment by wimh966** [comment]
您好，case 3: 对于当前block，weight重构的时候不感受该block的activation量化。但是block输入的获取是经过了前面所有层的量化。

**Comment by jiawei-liu1103** [comment]
好的，我想我大概明白了，多谢您的解答
