### ISSUE TITLE
Qdrop-BERT experiment configurations

### ISSUE THREAD

**Issue by penpaperkeycode** [wimh966/QDrop#6]
Hello :) 

First of all, it was a pleasure to see your cool papers and experimental results.

There is one question that I am facing, so I leave this issue here.

Among the experimental results, I am curious about the experimental setting for the BERT model on GLUE task. 
The paper did not explain how the block structure was established.
I would be very grateful if you could tell me about the detailed experimental settings.

**Comment by wimh966** [comment]
hi, I write it based on huggingface, take a BERT layer as a block. A BERT layer contains a MHA and a FFN. Other params are kept in same with ImageNet classification task.  If you have other problems, just let me know.
