### ISSUE TITLE
Unable to reproduce the results in paper for MobileNetV2

### ISSUE THREAD

**Issue by jiawei-liu1103** [wimh966/QDrop#8]
您好！我发现无法使用代码复现论文Tab 3中BRECQ量化配置下的QDROP（W2A2）MobileNetV2的结果。论文中的结果为13.05，可是我在设置了网络第一层输出为8比特（只在源码上修改了这一部分）之后，得到的结果仅为9.848，这是正常情况吗？修改部分的代码如下：
` a_list[0].bitwidth_refactor(8)`

**Comment by wimh966** [comment]
hi, can I ask that does the results on mbv2 reasonable if you do not set the output of first layer to 8-bit? Also, do other results like W2A4 and W4A4 on mbv2 reasonable, if you set the output of first layer to 8-bit.

**Comment by wimh966** [comment]
hi, can I ask that do the results on mbv2 align with paper if you do not set the output of first layer to 8-bit? Also, do the results like W2A4 and W4A4 on mbv2 align with paper, if you set the output of first layer to 8-bit.

**Comment by jiawei-liu1103** [comment]
感谢你如此迅速的答复，如果我设置第一层的输出8bit，w2a2和w2a4的结果与论文不对齐，具体结果分别为9.848（W2A2）和49.782（W2A4）。如果我设置第一层的输出不是8bit，那么只有w2a4的结果与论文不对齐，为49.566。除了提到的这一些其他的结果都与论文相符。
谢谢！

**Comment by wimh966** [comment]
It seems that there are issues about your experiments as I and other members have reached results in the paper. Do you use the accurate config in the readme? --weight should be set to 0.1 for mbv2 following BRECQ.

**Comment by jiawei-liu1103** [comment]
哦哦不好意思我没有注意到mbv2使用了不同的超参数，非常感谢你的解答！

**Comment by wimh966** [comment]
OK. If you have other problems, just let me know.
