### ISSUE TITLE
about the first layer quantization

### ISSUE THREAD

**Issue by andeyeluguo** [wimh966/QDrop#9]
你好,看了代码,发现的输入是normalize之后的,所以无论怎么做,确认下第一层只是权重量化吧.

**Comment by andeyeluguo** [comment]
我看着而有写实现是这层的权重和输入进行配套组合的量化,这个是权重和输出的量化,这个是基于 什么考虑的

**Comment by wimh966** [comment]
> 你好,看了代码,发现的输入是normalize之后的,所以无论怎么做,确认下第一层只是权重量化吧.

the first layer's input belongs to 0~255 and satisfies the requirement of 8-bit quantization. The later normalization is a linear transformation. That is to say, whether you add a quantizer to the activation after normalization will not incur any accuracy change.

**Comment by wimh966** [comment]
> 我看着而有写实现是这层的权重和输入进行配套组合的量化,这个是权重和输出的量化,这个是基于 什么考虑的

Quantizing output promises the next layer's input to be quantized. The difference between directly quantizing input and output is for multi-branches. And quantizing output can promise that the same activation corresponds to the same quantizer, which is friendly to hardware.
